//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicImport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Austria</string>
  <string>Belgium</string>
  <string>Canada</string>
  <string>Denmark</string>
  <string>Finland</string>
  <string>France</string>
  <string>Germany</string>
  <string>Iceland</string>
  <string>Italy</string>
  <string>Luxembourg</string>
  <string>Norway</string>
  <string>Portugal</string>
  <string>Spain</string>
  <string>Sweden</string>
  <string>Switzerland</string>
  <string>Netherlands</string>
  <string>UnitedKingdom</string>
  <string>UnitedStates</string>
  <string>NoCountry</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IncludeOnly {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IncludeOnly"]));
            }
        }
    }
}
